export type Product = {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  image: string;
  images: string[];
  originalPrice: number;
  salePrice: number;
  offerPrice?: number;
  discountPercentage: number;
  rating: number;
  reviewCount: number;
  stock: number;
  badge?: string;
  features: string[];
  specifications: Record<string, string>;
};

export const CATEGORIES = [
  "Mobiles",
  "Laptops",
  "Electronics",
  "TVs",
  "Appliances",
  "Audio",
  "Wearables",
  "Cameras",
  "Home & Kitchen",
  "Accessories",
] as const;

export type Category = (typeof CATEGORIES)[number];

function toProducts(
  rows: Omit<Product, "discountPercentage">[]
): Product[] {
  return rows.map((row) => ({
    ...row,
    discountPercentage: Math.round(
      ((row.originalPrice - row.salePrice) / row.originalPrice) * 100
    ),
  }));
}

export const products: Product[] = toProducts([
  /* ------------------------------ MOBILES ------------------------------ */
  {
    id: "mob-001",
    name: "iPhone 17 Pro Max 1 TB 17.42 cm (6.9), A19 Pro Chip, Best Battery Life in iPhone Ever",
    slug: "iphone-17-pro-max-1tb",
    description: "Apple's flagship iPhone with A19 Pro chip, 1TB storage, 6.9-inch display, and the best battery life ever in an iPhone.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/616-Eh2FbPL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/616-Eh2FbPL._SL1500_.jpg"],
    originalPrice: 189990,
    salePrice: 498,
    offerPrice: 498,
    rating: 4.8,
    reviewCount: 499,
    stock: 10,
    badge: "Flagship",
    features: ["A19 Pro Chip", "1TB Storage", "17.42 cm (6.9) Display", "Best Battery Life", "Advanced Camera System"],
    specifications: { Brand: "Apple", "Model Name": "iPhone 17 Pro Max", Storage: "1TB", RAM: "8GB", "Display Size": "6.9 inch", Battery: "Longest battery life", "Operating System": "iOS", "Network Type": "5G" },
  },
  {
    id: "mob-002",
    name: "Samsung Galaxy S26 Ultra 5G (16GB RAM, 1TB Storage) with Built-in Privacy Display, AI Phone",
    slug: "samsung-galaxy-s26-ultra-5g",
    description: "Premium Samsung flagship with 16GB RAM, 1TB storage, built-in privacy display, and advanced AI features.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71RLLn9RZxL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71RLLn9RZxL._SL1500_.jpg"],
    originalPrice: 189999,
    salePrice: 582,
    offerPrice: 582,
    rating: 4.7,
    reviewCount: 495,
    stock: 8,
    badge: "Premium",
    features: ["16GB RAM", "1TB Storage", "Built-in Privacy Display", "AI Features", "Advanced Camera"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy S26 Ultra", Storage: "1TB", RAM: "16GB", "Display": "Dynamic AMOLED", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-003",
    name: "iPhone 16 Pro Max 512 GB: 5G Mobile Phone with Camera Control, 4K 120 fps Dolby Vision",
    slug: "iphone-16-pro-max-512gb",
    description: "iPhone 16 Pro Max with 512GB storage, advanced camera control, and 4K 120 fps Dolby Vision recording.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61giwQtR1qL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61giwQtR1qL._SL1500_.jpg"],
    originalPrice: 164900,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.7,
    reviewCount: 491,
    stock: 12,
    badge: "Hot Deal",
    features: ["512GB Storage", "Camera Control", "4K 120 fps Dolby Vision", "A18 Pro Chip", "5G Connectivity"],
    specifications: { Brand: "Apple", "Model Name": "iPhone 16 Pro Max", Storage: "512GB", "Display": "6.9 inch Super Retina XDR", "Operating System": "iOS", "Network Type": "5G" },
  },
  {
    id: "mob-004",
    name: "iPhone 16 Plus 256 GB: 5G Mobile Phone with Camera Control, A18 Chip and a Big Boost in Battery Life",
    slug: "iphone-16-plus-256gb",
    description: "iPhone 16 Plus with 256GB storage, A18 chip, camera control, and impressive performance boost.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61Brhn4WBIL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61Brhn4WBIL._SL1500_.jpg"],
    originalPrice: 92999,
    salePrice: 352,
    offerPrice: 352,
    rating: 4.5,
    reviewCount: 485,
    stock: 20,
    badge: "Value Pick",
    features: ["256GB Storage", "A18 Chip", "Camera Control", "Big Boost in Performance", "5G Connectivity"],
    specifications: { Brand: "Apple", "Model Name": "iPhone 16 Plus", Storage: "256GB", "Display": "6.7 inch Super Retina XDR", "Operating System": "iOS", "Network Type": "5G" },
  },
  {
    id: "mob-005",
    name: "Samsung Galaxy S24 Ultra 5G AI Smartphone with Galaxy AI (12GB, 512GB Storage)",
    slug: "samsung-galaxy-s24-ultra-5g",
    description: "Samsung's AI-powered flagship with Galaxy AI, 12GB RAM, 512GB storage, and advanced camera capabilities.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/717Q2swzhBL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/717Q2swzhBL._SL1500_.jpg"],
    originalPrice: 164900,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.6,
    reviewCount: 429,
    stock: 15,
    badge: "Best Seller",
    features: ["12GB RAM", "512GB Storage", "Galaxy AI", "S Pen Support", "Advanced Camera"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy S24 Ultra", Storage: "512GB", RAM: "12GB", "Display": "6.8 inch Dynamic AMOLED", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-006",
    name: "OnePlus 15 | 16GB+512GB | India's First Snapdragon 8 Elite Gen 5 | 7300mAh Battery",
    slug: "oneplus-15-16gb-512gb",
    description: "OnePlus 15 with 16GB RAM, 512GB storage, Snapdragon 8 Elite Gen 5 processor, and massive 7300mAh battery.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/616kkUbRg4L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/616kkUbRg4L._SL1500_.jpg"],
    originalPrice: 83999,
    salePrice: 567,
    offerPrice: 567,
    rating: 4.6,
    reviewCount: 489,
    stock: 18,
    badge: "Hot Deal",
    features: ["16GB RAM", "512GB Storage", "Snapdragon 8 Elite Gen 5", "7300mAh Battery", "Fast Charging"],
    specifications: { Brand: "OnePlus", "Model Name": "OnePlus 15", Storage: "512GB", RAM: "16GB", Processor: "Snapdragon 8 Elite Gen 5", Battery: "7300mAh", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-007",
    name: "Samsung Galaxy S25 Ultra 5G AI Smartphone (12GB RAM, 1TB Storage)",
    slug: "samsung-galaxy-s25-ultra-5g",
    description: "Next-gen Samsung flagship with 12GB RAM, 1TB storage, advanced AI capabilities, and premium design.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61sU8OqBs4L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61sU8OqBs4L._SL1500_.jpg"],
    originalPrice: 165999,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.7,
    reviewCount: 490,
    stock: 6,
    badge: "Premium",
    features: ["12GB RAM", "1TB Storage", "AI Features", "Enhanced Camera System", "5G Connectivity"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy S25 Ultra", Storage: "1TB", RAM: "12GB", "Display": "6.8 inch Dynamic AMOLED", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-008",
    name: "vivo X300 Pro 5G (16GB RAM, 512GB Storage) with No Cost EMI",
    slug: "vivo-x300-pro-5g",
    description: "vivo X300 Pro with 16GB RAM, 512GB storage, 5G connectivity, and No Cost EMI option.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71Gxa9gpbnL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71Gxa9gpbnL._SL1500_.jpg"],
    originalPrice: 119999,
    salePrice: 842,
    offerPrice: 842,
    rating: 4.5,
    reviewCount: 482,
    stock: 14,
    badge: "Best Seller",
    features: ["16GB RAM", "512GB Storage", "No Cost EMI", "Advanced Camera", "5G Connectivity"],
    specifications: { Brand: "vivo", "Model Name": "X300 Pro", Storage: "512GB", RAM: "16GB", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-009",
    name: "iQOO 15 (16GB RAM, 512GB Storage) | Fastest Snapdragon 8 Elite Gen 5 Processor",
    slug: "iqoo-15-16gb-512gb",
    description: "iQOO 15 with 16GB RAM, 512GB storage, and the fastest Snapdragon 8 Elite Gen 5 processor.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61OB0B7FA-L._SL1200_.jpg",
    images: ["https://m.media-amazon.com/images/I/61OB0B7FA-L._SL1200_.jpg"],
    originalPrice: 83999,
    salePrice: 356,
    offerPrice: 356,
    rating: 4.6,
    reviewCount: 471,
    stock: 16,
    badge: "Hot Deal",
    features: ["16GB RAM", "512GB Storage", "Snapdragon 8 Elite Gen 5", "Fastest Processor", "5G Connectivity"],
    specifications: { Brand: "iQOO", "Model Name": "iQOO 15", Storage: "512GB", RAM: "16GB", Processor: "Snapdragon 8 Elite Gen 5", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-010",
    name: "realme GT 7 Pro (16GB+512GB) India's First Snapdragon 8 Elite Processor",
    slug: "realme-gt-7-pro",
    description: "realme GT 7 Pro with 16GB RAM, 512GB storage, and India's first Snapdragon 8 Elite processor.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71rFJVZsNNL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71rFJVZsNNL._SL1500_.jpg"],
    originalPrice: 74999,
    salePrice: 741,
    offerPrice: 741,
    rating: 4.4,
    reviewCount: 457,
    stock: 22,
    badge: "Mega Deal",
    features: ["16GB RAM", "512GB Storage", "Snapdragon 8 Elite Processor", "Fast Charging", "5G Connectivity"],
    specifications: { Brand: "realme", "Model Name": "GT 7 Pro", Storage: "512GB", RAM: "16GB", Processor: "Snapdragon 8 Elite", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-011",
    name: "Google Pixel 10 Pro XL (Moonstone, 256 GB) (16 GB RAM)",
    slug: "google-pixel-10-pro-xl",
    description: "Google Pixel 10 Pro XL with 16GB RAM, 256GB storage, Moonstone color, and pure Android experience.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61SYZ88UxmL._AC_SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61SYZ88UxmL._AC_SL1500_.jpg"],
    originalPrice: 124999,
    salePrice: 523,
    offerPrice: 523,
    rating: 4.7,
    reviewCount: 485,
    stock: 9,
    badge: "Premium",
    features: ["16GB RAM", "256GB Storage", "Pure Android Experience", "Advanced Camera", "5G Connectivity"],
    specifications: { Brand: "Google", "Model Name": "Pixel 10 Pro XL", Storage: "256GB", RAM: "16GB", Color: "Moonstone", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-012",
    name: "Samsung Galaxy Z Fold7 5G Smartphone with Galaxy AI (12GB RAM, 512GB Storage)",
    slug: "samsung-galaxy-z-fold7-5g",
    description: "Samsung Galaxy Z Fold7 with 12GB RAM, 512GB storage, Galaxy AI features, and foldable display.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61aBczVAabL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61aBczVAabL._SL1500_.jpg"],
    originalPrice: 186999,
    salePrice: 412,
    offerPrice: 412,
    rating: 4.7,
    reviewCount: 495,
    stock: 5,
    badge: "Premium",
    features: ["12GB RAM", "512GB Storage", "Galaxy AI", "Foldable Display", "5G Connectivity"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy Z Fold7", Storage: "512GB", RAM: "12GB", "Display": "Foldable Dynamic AMOLED", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-013",
    name: "Samsung Galaxy S25 5G Smartphone with Galaxy AI (12GB RAM, 256GB Storage)",
    slug: "samsung-galaxy-s25-5g",
    description: "Samsung Galaxy S25 with 12GB RAM, 256GB storage, Galaxy AI features, and 5G connectivity.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61p3FwE31-L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61p3FwE31-L._SL1500_.jpg"],
    originalPrice: 80999,
    salePrice: 632,
    offerPrice: 632,
    rating: 4.5,
    reviewCount: 413,
    stock: 25,
    badge: "Best Seller",
    features: ["12GB RAM", "256GB Storage", "Galaxy AI", "5G Connectivity", "Advanced Camera"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy S25", Storage: "256GB", RAM: "12GB", "Display": "6.2 inch Dynamic AMOLED", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-014",
    name: "VIVO X200 FE 5G (16GB RAM, 512GB Storage)",
    slug: "vivo-x200-fe-5g",
    description: "vivo X200 FE with 16GB RAM, 512GB storage, and 5G connectivity.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71QkSIVns8L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71QkSIVns8L._SL1500_.jpg"],
    originalPrice: 64999,
    salePrice: 623,
    offerPrice: 623,
    rating: 4.4,
    reviewCount: 411,
    stock: 20,
    badge: "Value Pick",
    features: ["16GB RAM", "512GB Storage", "5G Connectivity", "Advanced Camera", "Long Battery Life"],
    specifications: { Brand: "vivo", "Model Name": "X200 FE", Storage: "512GB", RAM: "16GB", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-015",
    name: "HONOR X9c 5G Dual SIM (8GB RAM, 256GB Storage) | Ultra Durable | 108MP AI OIS Camera",
    slug: "honor-x9c-5g",
    description: "HONOR X9c with 8GB RAM, 256GB storage, ultra-durable build, and 108MP AI OIS camera.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71E0Y55Oo3L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71E0Y55Oo3L._SL1500_.jpg"],
    originalPrice: 27999,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.3,
    reviewCount: 469,
    stock: 30,
    badge: "Hot Deal",
    features: ["8GB RAM", "256GB Storage", "Ultra Durable", "108MP AI OIS Camera", "5G Connectivity"],
    specifications: { Brand: "HONOR", "Model Name": "X9c", Storage: "256GB", RAM: "8GB", Camera: "108MP AI OIS", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-016",
    name: "Samsung Galaxy M36 5G (8 GB RAM, 256 GB Storage) | Circle to Search | Google Gemini",
    slug: "samsung-galaxy-m36-5g",
    description: "Samsung Galaxy M36 with 8GB RAM, 256GB storage, Circle to Search feature, and Google Gemini integration.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61CK00kuV5L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61CK00kuV5L._SL1500_.jpg"],
    originalPrice: 27999,
    salePrice: 345,
    offerPrice: 345,
    rating: 4.3,
    reviewCount: 437,
    stock: 35,
    badge: "Best Seller",
    features: ["8GB RAM", "256GB Storage", "Circle to Search", "Google Gemini", "5G Connectivity"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy M36", Storage: "256GB", RAM: "8GB", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-017",
    name: "realme 15 Pro 5G Smartphone 12+256GB Purple, 4K 60FPS, 144Hz HyperGlow 4D Curve Display",
    slug: "realme-15-pro-5g",
    description: "realme 15 Pro with 12GB RAM, 256GB storage, 4K 60FPS video, 144Hz HyperGlow 4D Curve display.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61lcTmjeTUL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61lcTmjeTUL._SL1500_.jpg"],
    originalPrice: 39999,
    salePrice: 462,
    offerPrice: 462,
    rating: 4.4,
    reviewCount: 439,
    stock: 18,
    badge: "Hot Deal",
    features: ["12GB RAM", "256GB Storage", "4K 60FPS", "144Hz HyperGlow 4D Curve Display", "5G Connectivity"],
    specifications: { Brand: "realme", "Model Name": "15 Pro", Storage: "256GB", RAM: "12GB", Color: "Purple", "Display": "144Hz HyperGlow 4D Curve", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-018",
    name: "Redmi Note 14 Pro 5G 8GB RAM 256GB Storage | 50 MP Sony Camera Setup | Corning Gorilla Glass Victus 2",
    slug: "redmi-note-14-pro-5g",
    description: "Redmi Note 14 Pro with 8GB RAM, 256GB storage, 50MP Sony camera setup, and Corning protection.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71fsSg9xvvL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71fsSg9xvvL._SL1500_.jpg"],
    originalPrice: 30999,
    salePrice: 423,
    offerPrice: 423,
    rating: 4.3,
    reviewCount: 444,
    stock: 28,
    badge: "Best Seller",
    features: ["8GB RAM", "256GB Storage", "50MP Sony Camera", "Corning Gorilla Glass Victus 2", "5G Connectivity"],
    specifications: { Brand: "Redmi", "Model Name": "Note 14 Pro", Storage: "256GB", RAM: "8GB", Camera: "50MP Sony", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-019",
    name: "OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable 144FPS Gaming | Dual 50MP Flagship Camera",
    slug: "oneplus-nord-5",
    description: "OnePlus Nord 5 with Snapdragon 8s Gen 3, 144FPS gaming, dual 50MP camera, and OnePlus AI features.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/61OtOTTpzxL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61OtOTTpzxL._SL1500_.jpg"],
    originalPrice: 99900,
    salePrice: 523,
    offerPrice: 523,
    rating: 4.4,
    reviewCount: 429,
    stock: 15,
    badge: "Best Seller",
    features: ["Snapdragon 8s Gen 3", "144FPS Gaming", "Dual 50MP Camera", "OnePlus AI", "5G Connectivity"],
    specifications: { Brand: "OnePlus", "Model Name": "Nord 5", Storage: "512GB", RAM: "12GB", Processor: "Snapdragon 8s Gen 3", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-020",
    name: "realme NARZO 80 Pro 5G (8GB+256GB) | Segment's 1st MediaTek Dimensity 7400 Chipset",
    slug: "realme-narzo-80-pro",
    description: "realme NARZO 80 Pro with MediaTek Dimensity 7400, 6000mAh battery, and IP69 waterproof rating.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71O+42MuShL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71O+42MuShL._SL1500_.jpg"],
    originalPrice: 25999,
    salePrice: 451,
    offerPrice: 451,
    rating: 4.3,
    reviewCount: 421,
    stock: 25,
    badge: "Hot Deal",
    features: ["MediaTek Dimensity 7400", "6000mAh Battery", "80W Ultra Charge", "IP69 Waterproof", "5G Connectivity"],
    specifications: { Brand: "realme", "Model Name": "NARZO 80 Pro", Storage: "256GB", RAM: "8GB", Processor: "MediaTek Dimensity 7400", Battery: "6000mAh", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-021",
    name: "CMF Phone 2 Pro (8GB RAM, 256GB Storage)",
    slug: "cmf-phone-2-pro",
    description: "CMF Phone 2 Pro with 8GB RAM, 256GB storage, and modern design.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71l4ZcTLEYL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71l4ZcTLEYL._SL1500_.jpg"],
    originalPrice: 24999,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.2,
    reviewCount: 422,
    stock: 30,
    badge: "Value Pick",
    features: ["8GB RAM", "256GB Storage", "Modern Design", "5G Connectivity", "Clean Software"],
    specifications: { Brand: "CMF", "Model Name": "Phone 2 Pro", Storage: "256GB", RAM: "8GB", "Operating System": "Android", "Network Type": "5G" },
  },
  {
    id: "mob-022",
    name: "Lava Agni 3 5G (8GB+256GB) | India's 1st Dual AMOLED | 1.5K Curved Display",
    slug: "lava-agni-3-5g",
    description: "Lava Agni 3 with dual AMOLED display, Dimensity 7300X, and 66W fast charging.",
    category: "Mobiles",
    image: "https://m.media-amazon.com/images/I/71vZUOuFWfL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71vZUOuFWfL._SL1500_.jpg"],
    originalPrice: 27999,
    salePrice: 425,
    offerPrice: 425,
    rating: 4.3,
    reviewCount: 428,
    stock: 20,
    badge: "Best Seller",
    features: ["Dual AMOLED Display", "1.5K Curved Display", "Dimensity 7300X", "66W Fast Charge", "5G Connectivity"],
    specifications: { Brand: "Lava", "Model Name": "Agni 3", Storage: "256GB", RAM: "8GB", Processor: "Dimensity 7300X", "Operating System": "Android", "Network Type": "5G" },
  },

  /* ------------------------------ LAPTOPS & COMPUTERS ------------------------------ */
  {
    id: "lap-001",
    name: "ASUS ROG Zephyrus G14, AMD Ryzen AI 9 HX 370 Gaming Laptop RTX 5070 Ti",
    slug: "asus-rog-zephyrus-g14",
    description: "ASUS ROG Zephyrus G14 gaming laptop with AMD Ryzen AI 9 HX 370 processor and RTX 5070 Ti graphics.",
    category: "Laptops",
    image: "https://m.media-amazon.com/images/I/71uPoxSrtQL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71uPoxSrtQL._SL1500_.jpg"],
    originalPrice: 291190,
    salePrice: 423,
    offerPrice: 423,
    rating: 4.8,
    reviewCount: 499,
    stock: 4,
    badge: "Flagship",
    features: ["AMD Ryzen AI 9 HX 370", "RTX 5070 Ti Graphics", "14-inch Display", "Gaming Performance", "Advanced Cooling"],
    specifications: { Brand: "ASUS", "Model Name": "ROG Zephyrus G14", Processor: "AMD Ryzen AI 9 HX 370", Graphics: "RTX 5070 Ti", "Display": "14 inch", "Operating System": "Windows 11" },
  },
  {
    id: "lap-002",
    name: "HP All-in-One PC 13th Gen Intel Core i5 27 (68.6cm) FHD 16GB RAM, 1TB SSD",
    slug: "hp-all-in-one-27",
    description: "HP All-in-One PC with 13th Gen Intel Core i5, 27-inch FHD display, 16GB RAM, and 1TB SSD.",
    category: "Laptops",
    image: "https://m.media-amazon.com/images/I/71Q0W5eK2SL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71Q0W5eK2SL._SL1500_.jpg"],
    originalPrice: 117990,
    salePrice: 425,
    offerPrice: 425,
    rating: 4.4,
    reviewCount: 425,
    stock: 8,
    badge: "Best Seller",
    features: ["13th Gen Intel Core i5", "27-inch FHD Display", "16GB RAM", "1TB SSD", "All-in-One Design"],
    specifications: { Brand: "HP", Processor: "13th Gen Intel Core i5", RAM: "16GB", Storage: "1TB SSD", "Display": "27 inch FHD", "Operating System": "Windows 11" },
  },
  {
    id: "lap-003",
    name: "Apple 2025 MacBook Pro Laptop with M5 chip, 10-core CPU and 10-core GPU",
    slug: "apple-macbook-pro-m5",
    description: "Apple MacBook Pro with M5 chip, 10-core CPU, 10-core GPU, built for Apple Intelligence.",
    category: "Laptops",
    image: "https://m.media-amazon.com/images/I/61opqQEBUxL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61opqQEBUxL._SL1500_.jpg"],
    originalPrice: 189900,
    salePrice: 680,
    offerPrice: 680,
    rating: 4.8,
    reviewCount: 499,
    stock: 6,
    badge: "Premium",
    features: ["M5 Chip", "10-core CPU", "10-core GPU", "Built for Apple Intelligence", "Retina Display"],
    specifications: { Brand: "Apple", "Model Name": "MacBook Pro", Processor: "M5", "CPU": "10-core", "GPU": "10-core", "Operating System": "macOS" },
  },
  {
    id: "lap-004",
    name: "Dell Alienware M18 R2 Gaming Laptop - 18 QHD+ 165Hz 3ms Display, Intel Core i9 14900HX",
    slug: "dell-alienware-m18-r2",
    description: "Dell Alienware M18 R2 gaming laptop with 18-inch QHD+ 165Hz display, Intel Core i9 14900HX, and 32GB RAM.",
    category: "Laptops",
    image: "https://m.media-amazon.com/images/I/711eTqJwAyL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/711eTqJwAyL._SL1500_.jpg"],
    originalPrice: 471999,
    salePrice: 752,
    offerPrice: 752,
    rating: 4.8,
    reviewCount: 999,
    stock: 3,
    badge: "Flagship",
    features: ["18-inch QHD+ 165Hz Display", "Intel Core i9 14900HX", "32GB RAM", "Premium Gaming Performance", "Advanced Cooling"],
    specifications: { Brand: "Dell", "Model Name": "Alienware M18 R2", Processor: "Intel Core i9 14900HX", RAM: "32GB", "Display": "18 inch QHD+ 165Hz", "Operating System": "Windows 11" },
  },

  /* -------------------------------- TABLETS -------------------------------- */
  {
    id: "tab-001",
    name: "Apple iPad Pro 11 (M4): Ultra Retina XDR Display, 2TB, 12MP Camera",
    slug: "apple-ipad-pro-11-m4",
    description: "Apple iPad Pro with M4 chip, 11-inch Ultra Retina XDR display, 2TB storage, and 12MP camera.",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/71bBrftkB+L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71bBrftkB+L._SL1500_.jpg"],
    originalPrice: 219900,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.7,
    reviewCount: 499,
    stock: 5,
    badge: "Premium",
    features: ["M4 Chip", "11-inch Ultra Retina XDR", "2TB Storage", "12MP Camera", "Apple Pencil Support"],
    specifications: { Brand: "Apple", "Model Name": "iPad Pro 11", Processor: "M4", Storage: "2TB", Display: "Ultra Retina XDR", Camera: "12MP", "Operating System": "iPadOS" },
  },
  {
    id: "tab-002",
    name: "OnePlus Pad 3 World's Fastest Snapdragon 8 Elite Processor, 13.2 3.4k Screen",
    slug: "oneplus-pad-3",
    description: "OnePlus Pad 3 with Snapdragon 8 Elite processor, 13.2-inch 3.4K display, and premium build.",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/61Haauo2GGL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61Haauo2GGL._SL1500_.jpg"],
    originalPrice: 54999,
    salePrice: 542,
    offerPrice: 542,
    rating: 4.5,
    reviewCount: 445,
    stock: 12,
    badge: "Best Seller",
    features: ["Snapdragon 8 Elite", "13.2-inch 3.4K Screen", "Premium Build", "Fast Performance", "Long Battery Life"],
    specifications: { Brand: "OnePlus", "Model Name": "Pad 3", Processor: "Snapdragon 8 Elite", Display: "13.2 inch 3.4K", "Operating System": "Android" },
  },

  /* ------------------------------ CAMERAS ------------------------------ */
  {
    id: "cam-001",
    name: "Canon EOS R10 24.2MP RF-S18-150 F/3.5-6.3 IS STM Mirrorless Camera",
    slug: "canon-eos-r10",
    description: "Canon EOS R10 mirrorless camera with 24.2MP sensor, RF-S18-150mm lens, and 4K video recording.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/61Qwa-2f60L.jpg",
    images: ["https://m.media-amazon.com/images/I/61Qwa-2f60L.jpg"],
    originalPrice: 117995,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.6,
    reviewCount: 405,
    stock: 6,
    badge: "Best Seller",
    features: ["24.2MP Sensor", "RF-S18-150mm Lens", "4K Video", "Mirrorless Design", "Advanced Autofocus"],
    specifications: { Brand: "Canon", "Model Name": "EOS R10", Sensor: "24.2MP", Lens: "RF-S18-150mm", Video: "4K", Type: "Mirrorless" },
  },
  {
    id: "cam-002",
    name: "Sony Alpha ZV-E10L 24.2 Mega Pixel Interchangeable-Lens Mirrorless vlog Camera",
    slug: "sony-alpha-zv-e10l",
    description: "Sony Alpha ZV-E10L vlog camera with 24.2MP sensor, interchangeable lens, and 4K movie recording.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/71AJ6LicHkL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71AJ6LicHkL._SL1500_.jpg"],
    originalPrice: 69990,
    salePrice: 456,
    offerPrice: 456,
    rating: 4.5,
    reviewCount: 410,
    stock: 8,
    badge: "Hot Deal",
    features: ["24.2MP Sensor", "Interchangeable Lens", "4K Movie Recording", "Vlog Features", "Advanced Autofocus"],
    specifications: { Brand: "Sony", "Model Name": "Alpha ZV-E10L", Sensor: "24.2MP", Video: "4K", Type: "Mirrorless", Lens: "16-50mm" },
  },
  {
    id: "cam-003",
    name: "GoPro Hero12 Black - Waterproof Action Camera With 5.3K60 Ultra HD Video",
    slug: "gopro-hero12-black",
    description: "GoPro Hero12 Black waterproof action camera with 5.3K60 video, 27MP photos, and HDR.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/61wsvCGXqnL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61wsvCGXqnL._SL1500_.jpg"],
    originalPrice: 59999,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.4,
    reviewCount: 411,
    stock: 10,
    badge: "Best Seller",
    features: ["5.3K60 Video", "27MP Photos", "HDR", "Waterproof", "Image Stabilization"],
    specifications: { Brand: "GoPro", "Model Name": "Hero12 Black", Video: "5.3K60", Photos: "27MP", Waterproof: "Yes" },
  },
  {
    id: "cam-004",
    name: "insta360 X4 - 8K Waterproof 360 Action Camera, 4K Wide-Angle Video",
    slug: "insta360-x4",
    description: "Insta360 X4 360 action camera with 8K video, waterproof design, and invisible selfie stick effect.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/717MMGU6XmL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/717MMGU6XmL._SL1500_.jpg"],
    originalPrice: 59999,
    salePrice: 542,
    offerPrice: 542,
    rating: 4.5,
    reviewCount: 434,
    stock: 7,
    badge: "Hot Deal",
    features: ["8K Video", "4K Wide-Angle Video", "Waterproof", "Invisible Selfie Stick", "360 Capture"],
    specifications: { Brand: "insta360", "Model Name": "X4", Video: "8K", Waterproof: "Yes", Type: "360 Action Camera" },
  },

  /* -------------------------------- TVs -------------------------------- */
  {
    id: "tv-001",
    name: "Samsung 214 cm (85 inches) 4K Ultra HD Smart Neo QLED TV QA85QN90BAKXXL",
    slug: "samsung-85-inch-neo-qled",
    description: "Samsung 85-inch 4K Ultra HD Smart Neo QLED TV with premium picture quality and smart features.",
    category: "TVs",
    image: "https://m.media-amazon.com/images/I/91b1B9Pjd2L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/91b1B9Pjd2L._SL1500_.jpg"],
    originalPrice: 471900,
    salePrice: 536,
    offerPrice: 536,
    rating: 4.8,
    reviewCount: 499,
    stock: 3,
    badge: "Flagship",
    features: ["85-inch 4K Ultra HD", "Neo QLED Technology", "Smart TV Features", "Premium Picture Quality", "Advanced Audio"],
    specifications: { Brand: "Samsung", "Model Name": "QA85QN90BAKXXL", "Screen Size": "85 inch", Resolution: "4K Ultra HD", Display: "Neo QLED", "Smart Features": "Yes" },
  },
  {
    id: "tv-002",
    name: "LG 139 cm (55 inches) 4K Ultra HD Smart OLED TV 55B2PSA",
    slug: "lg-55-inch-oled-tv",
    description: "LG 55-inch 4K Ultra HD Smart OLED TV with perfect blacks and stunning picture quality.",
    category: "TVs",
    image: "https://m.media-amazon.com/images/I/810ni0-df5L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/810ni0-df5L._SL1500_.jpg"],
    originalPrice: 147490,
    salePrice: 526,
    offerPrice: 526,
    rating: 4.7,
    reviewCount: 489,
    stock: 5,
    badge: "Premium",
    features: ["55-inch 4K Ultra HD", "OLED Technology", "Perfect Blacks", "Smart TV Features", "Advanced Picture Processing"],
    specifications: { Brand: "LG", "Model Name": "55B2PSA", "Screen Size": "55 inch", Resolution: "4K Ultra HD", Display: "OLED", "Smart Features": "Yes" },
  },
  {
    id: "tv-003",
    name: "Philips 109 cm (43 inches) 8100 Series 4K Ultra HD Smart QLED Google TV 43PQT8100/94",
    slug: "philips-43-inch-qled-google-tv",
    description: "Philips 43-inch 4K Ultra HD Smart QLED Google TV with advanced features and smart connectivity.",
    category: "TVs",
    image: "https://m.media-amazon.com/images/I/81kIGY7STpL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81kIGY7STpL._SL1500_.jpg"],
    originalPrice: 29999,
    salePrice: 652,
    offerPrice: 652,
    rating: 4.3,
    reviewCount: 431,
    stock: 15,
    badge: "Best Seller",
    features: ["43-inch 4K Ultra HD", "QLED Technology", "Google TV", "Smart Features", "Advanced Picture Quality"],
    specifications: { Brand: "Philips", "Model Name": "43PQT8100/94", "Screen Size": "43 inch", Resolution: "4K Ultra HD", Display: "QLED", "Smart Features": "Google TV" },
  },
  {
    id: "tv-004",
    name: "Sony 139 cm (55 inches) BRAVIA 5 4K Ultra HD Smart Mini LED Google TV K-55XR50",
    slug: "sony-55-inch-bravia-5",
    description: "Sony 55-inch 4K Ultra HD Smart Mini LED Google TV with BRAVIA technology and premium picture quality.",
    category: "TVs",
    image: "https://m.media-amazon.com/images/I/81dC067BCML._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81dC067BCML._SL1500_.jpg"],
    originalPrice: 69999,
    salePrice: 652,
    offerPrice: 652,
    rating: 4.6,
    reviewCount: 475,
    stock: 8,
    badge: "Premium",
    features: ["55-inch 4K Ultra HD", "Mini LED Technology", "Google TV", "BRAVIA Technology", "Premium Picture Quality"],
    specifications: { Brand: "Sony", "Model Name": "K-55XR50", "Screen Size": "55 inch", Resolution: "4K Ultra HD", Display: "Mini LED", "Smart Features": "Google TV" },
  },
  {
    id: "tv-005",
    name: "Xiaomi 80 cm (32 inch) A HD Ready Smart Google LED TV L32MB-AIN",
    slug: "xiaomi-32-inch-google-tv",
    description: "Xiaomi 32-inch HD Ready Smart Google LED TV with built-in Google TV and smart features.",
    category: "TVs",
    image: "https://m.media-amazon.com/images/I/81JlyfjRtML._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81JlyfjRtML._SL1500_.jpg"],
    originalPrice: 24999,
    salePrice: 652,
    offerPrice: 652,
    rating: 4.2,
    reviewCount: 409,
    stock: 20,
    badge: "Value Pick",
    features: ["32-inch HD Ready", "Google TV", "Smart Features", "LED Display", "Affordable Price"],
    specifications: { Brand: "Xiaomi", "Model Name": "L32MB-AIN", "Screen Size": "32 inch", Resolution: "HD Ready", Display: "LED", "Smart Features": "Google TV" },
  },

  /* ----------------------------- AUDIO ----------------------------- */
  {
    id: "aud-001",
    name: "Sony WH-1000XM6 The Best Wireless Noise Canceling Headphones, HD NC Processor QN3",
    slug: "sony-wh-1000xm6",
    description: "Sony WH-1000XM6 wireless noise canceling headphones with HD NC Processor QN3 and studio-quality sound.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/51432EoghOL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51432EoghOL._SL1500_.jpg"],
    originalPrice: 49999,
    salePrice: 522,
    offerPrice: 522,
    rating: 4.7,
    reviewCount: 401,
    stock: 12,
    badge: "Best Seller",
    features: ["HD NC Processor QN3", "12 Microphones", "Adaptive NC Optimizer", "Studio-Quality Sound", "Wireless Design"],
    specifications: { Brand: "Sony", "Model Name": "WH-1000XM6", Type: "Over-Ear Wireless", "Noise Cancellation": "Yes", "Battery Life": "Up to 40 hours" },
  },
  {
    id: "aud-002",
    name: "Samsung Galaxy Buds3 Pro | Silver | Wireless Earbuds | Powered by Galaxy AI",
    slug: "samsung-galaxy-buds3-pro",
    description: "Samsung Galaxy Buds3 Pro wireless earbuds with Galaxy AI, active noise cancellation, and 37hrs battery.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/71xB+tcn-ZL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71xB+tcn-ZL._SL1500_.jpg"],
    originalPrice: 24999,
    salePrice: 635,
    offerPrice: 635,
    rating: 4.6,
    reviewCount: 400,
    stock: 25,
    badge: "Hot Deal",
    features: ["Galaxy AI", "Active Noise Cancellation", "37hrs Battery", "360 Surround Sound", "IP57 Water Resistant"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy Buds3 Pro", Type: "TWS Earbuds", Battery: "37hrs", "Noise Cancellation": "Yes", "Water Resistance": "IP57" },
  },
  {
    id: "aud-003",
    name: "Sony INZONE Buds WF-G700N Truly Wireless Noise Cancelling Gaming in-Ear Earbuds",
    slug: "sony-inzone-buds",
    description: "Sony INZONE Buds wireless gaming earbuds with noise cancellation, 24 hour battery, and 360 Spatial Sound.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/71o6WIakGiL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71o6WIakGiL._SL1500_.jpg"],
    originalPrice: 22999,
    salePrice: 465,
    offerPrice: 465,
    rating: 4.4,
    reviewCount: 439,
    stock: 15,
    badge: "Best Seller",
    features: ["24 Hour Battery", "360 Spatial Sound", "30ms Low Latency", "USB-C Dongle", "LE Audio (LC3)"],
    specifications: { Brand: "Sony", "Model Name": "INZONE Buds WF-G700N", Type: "Gaming Earbuds", Battery: "24hrs", "Noise Cancellation": "Yes" },
  },
  {
    id: "aud-004",
    name: "Apple AirPods Pro 3 Wireless Earbuds, Active Noise Cancellation, Live Translation",
    slug: "apple-airpods-pro-3",
    description: "Apple AirPods Pro 3 with active noise cancellation, live translation, heart rate sensing, and spatial audio.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/61o7EzoRpBL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61o7EzoRpBL._SL1500_.jpg"],
    originalPrice: 25900,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.7,
    reviewCount: 403,
    stock: 18,
    badge: "Premium",
    features: ["Active Noise Cancellation", "Live Translation", "Heart Rate Sensing", "Spatial Audio", "USB-C Charging"],
    specifications: { Brand: "Apple", "Model Name": "AirPods Pro 3", Type: "TWS Earbuds", "Noise Cancellation": "Yes", "Spatial Audio": "Yes" },
  },
  {
    id: "aud-005",
    name: "OnePlus Bullets Wireless Z3 in Ear Neckband with 12.4Mm Drivers, 3D Spatial Audio",
    slug: "oneplus-bullets-wireless-z3",
    description: "OnePlus Bullets Wireless Z3 neckband earbuds with 12.4mm drivers, 3D spatial audio, and AI call noise cancellation.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/51vT4GzBObL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51vT4GzBObL._SL1500_.jpg"],
    originalPrice: 2999,
    salePrice: 526,
    offerPrice: 526,
    rating: 4.2,
    reviewCount: 323,
    stock: 40,
    badge: "Value Pick",
    features: ["12.4mm Drivers", "3D Spatial Audio", "10 Mins Charge for 27 Hrs Playback", "AI Call Noise Cancellation", "BT5.4"],
    specifications: { Brand: "OnePlus", "Model Name": "Bullets Wireless Z3", Type: "Neckband", "Battery Life": "Up to 27 hours", "Bluetooth": "5.4" },
  },
  {
    id: "aud-006",
    name: "JBL Boombox 3 Wi-Fi, Wireless Portable Bluetooth Speaker, 24H Playtime, Deepest Bass",
    slug: "jbl-boombox-3-wifi",
    description: "JBL Boombox 3 Wi-Fi portable speaker with 24H playtime, deepest bass, and built-in powerbank.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/714VxAvzVAL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/714VxAvzVAL._SL1500_.jpg"],
    originalPrice: 59999,
    salePrice: 542,
    offerPrice: 542,
    rating: 4.5,
    reviewCount: 423,
    stock: 8,
    badge: "Best Seller",
    features: ["24H Playtime", "Deepest Bass", "Built-in Powerbank", "Wi-Fi with AirPlay", "IP67 Water Resistant"],
    specifications: { Brand: "JBL", "Model Name": "Boombox 3 Wi-Fi", Type: "Portable Speaker", Battery: "24hrs", "Water Resistance": "IP67", Connectivity: "Wi-Fi, Bluetooth" },
  },
  {
    id: "aud-007",
    name: "Bose New QuietComfort Wireless Noise Cancelling Earbuds",
    slug: "bose-quietcomfort-earbuds",
    description: "Bose QuietComfort wireless earbuds with active noise cancellation and up to 8.5 hours of battery life.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/61qIEvCy6+L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61qIEvCy6+L._SL1500_.jpg"],
    originalPrice: 16900,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.5,
    reviewCount: 416,
    stock: 20,
    badge: "Best Seller",
    features: ["Active Noise Cancellation", "Up to 8.5 Hours Battery", "Comfortable Fit", "Premium Sound", "Bluetooth Connectivity"],
    specifications: { Brand: "Bose", "Model Name": "QuietComfort", Type: "TWS Earbuds", Battery: "8.5hrs", "Noise Cancellation": "Yes" },
  },
  {
    id: "aud-008",
    name: "EarFun Air Pro 4 Hybrid Adaptive Noise Canceling Wireless Earbuds",
    slug: "earfun-air-pro-4",
    description: "EarFun Air Pro 4 earbuds with hybrid adaptive noise cancellation, Qualcomm Snapdragon Sound, and LDAC Hi-Res Audio.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/6157hOQ82xL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/6157hOQ82xL._SL1500_.jpg"],
    originalPrice: 10999,
    salePrice: 526,
    offerPrice: 526,
    rating: 4.4,
    reviewCount: 391,
    stock: 25,
    badge: "Hot Deal",
    features: ["Hybrid Adaptive ANC", "Qualcomm Snapdragon Sound", "aptX Lossless", "LDAC Hi-Res Audio", "52H Battery"],
    specifications: { Brand: "EarFun", "Model Name": "Air Pro 4", Type: "TWS Earbuds", "Noise Cancellation": "Hybrid Adaptive", Battery: "52hrs" },
  },
  {
    id: "aud-009",
    name: "soundcore by Anker Sport X10 True Wireless Bluetooth Sport Earbuds",
    slug: "soundcore-sport-x10",
    description: "Soundcore Sport X10 true wireless earbuds with rotatable over-ear hooks, deep bass, and IPX7 waterproof.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/51UUCeUcWIL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51UUCeUcWIL._SL1500_.jpg"],
    originalPrice: 15999,
    salePrice: 521,
    offerPrice: 521,
    rating: 4.3,
    reviewCount: 375,
    stock: 30,
    badge: "Value Pick",
    features: ["Rotatable Over-Ear Hooks", "Deep Bass", "IPX7 Waterproof", "Fast Charge", "Sport Design"],
    specifications: { Brand: "soundcore by Anker", "Model Name": "Sport X10", Type: "Sport Earbuds", "Water Resistance": "IPX7", Battery: "Fast Charge" },
  },
  {
    id: "aud-010",
    name: "Bose New QuietComfort Ultra Wireless Noise Cancelling Earbuds",
    slug: "bose-quietcomfort-ultra",
    description: "Bose QuietComfort Ultra wireless earbuds with spatial audio and world-class noise cancellation.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/513NQdmdMXL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/513NQdmdMXL._SL1500_.jpg"],
    originalPrice: 25990,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.6,
    reviewCount: 378,
    stock: 15,
    badge: "Premium",
    features: ["Spatial Audio", "World-Class Noise Cancellation", "Premium Sound", "Comfortable Design", "Bluetooth Connectivity"],
    specifications: { Brand: "Bose", "Model Name": "QuietComfort Ultra", Type: "TWS Earbuds", "Noise Cancellation": "Yes", "Spatial Audio": "Yes" },
  },
  {
    id: "aud-011",
    name: "Sennheiser Momentum 4 Wireless Over Ear Headphones, German Design, ANC",
    slug: "sennheiser-momentum-4",
    description: "Sennheiser Momentum 4 wireless over-ear headphones with German design, ANC, and 60h battery.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/71sLOtsK2UL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71sLOtsK2UL._SL1500_.jpg"],
    originalPrice: 34990,
    salePrice: 652,
    offerPrice: 652,
    rating: 4.6,
    reviewCount: 433,
    stock: 10,
    badge: "Premium",
    features: ["German Design", "ANC", "60h Battery", "Customizable Sound", "4 Digital Mics"],
    specifications: { Brand: "Sennheiser", "Model Name": "Momentum 4", Type: "Over-Ear Wireless", Battery: "60hrs", "Noise Cancellation": "Yes" },
  },
  {
    id: "aud-012",
    name: "Apple AirPods Max Wireless Over-Ear Headphones, Pro-Level Active Noise Cancellation",
    slug: "apple-airpods-max",
    description: "Apple AirPods Max over-ear headphones with pro-level active noise cancellation and personalized spatial audio.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/71RJCexaxiL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71RJCexaxiL._SL1500_.jpg"],
    originalPrice: 59900,
    salePrice: 425,
    offerPrice: 425,
    rating: 4.7,
    reviewCount: 421,
    stock: 8,
    badge: "Premium",
    features: ["Pro-Level Active Noise Cancellation", "Transparency Mode", "Personalized Spatial Audio", "USB-C Charging", "Premium Build"],
    specifications: { Brand: "Apple", "Model Name": "AirPods Max", Type: "Over-Ear Wireless", "Noise Cancellation": "Pro-Level", "Spatial Audio": "Yes" },
  },
  {
    id: "aud-013",
    name: "OnePlus Buds 3 in Ear TWS Bluetooth Earbuds with Upto 49dB Smart Adaptive Noise Cancellation",
    slug: "oneplus-buds-3",
    description: "OnePlus Buds 3 with 49dB smart adaptive noise cancellation, Hi-Res sound, and sliding volume control.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/51h7CQTRJ1L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51h7CQTRJ1L._SL1500_.jpg"],
    originalPrice: 6999,
    salePrice: 651,
    offerPrice: 651,
    rating: 4.4,
    reviewCount: 395,
    stock: 35,
    badge: "Best Seller",
    features: ["49dB Smart Adaptive ANC", "Hi-Res Sound", "Sliding Volume Control", "10mins for 7Hours Fast Charging", "44Hrs Playback"],
    specifications: { Brand: "OnePlus", "Model Name": "Buds 3", Type: "TWS Earbuds", "Noise Cancellation": "49dB", Battery: "44hrs" },
  },
  {
    id: "aud-014",
    name: "HyperX Cloud Alpha Wireless - Gaming Headset for PC, 300-hour battery life",
    slug: "hyperx-cloud-alpha-wireless",
    description: "HyperX Cloud Alpha Wireless gaming headset with 300-hour battery life for PC gaming.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/51A-WtZZl4L._SL1000_.jpg",
    images: ["https://m.media-amazon.com/images/I/51A-WtZZl4L._SL1000_.jpg"],
    originalPrice: 33999,
    salePrice: 585,
    offerPrice: 585,
    rating: 4.5,
    reviewCount: 359,
    stock: 12,
    badge: "Best Seller",
    features: ["300-hour battery life", "Gaming Headset", "Wireless", "PC Compatible", "Premium Sound"],
    specifications: { Brand: "HyperX", "Model Name": "Cloud Alpha Wireless", Type: "Gaming Headset", Battery: "300hrs", Connectivity: "Wireless" },
  },
  {
    id: "aud-015",
    name: "realme Buds Wireless 5 ANC in Ear Bluetooth Headphones, 50dB ANC",
    slug: "realme-buds-wireless-5",
    description: "realme Buds Wireless 5 neckband headphones with 50dB ANC, 13.6mm drivers, and 38hrs playback.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/412oiCcU6SL._SL1000_.jpg",
    images: ["https://m.media-amazon.com/images/I/412oiCcU6SL._SL1000_.jpg"],
    originalPrice: 2799,
    salePrice: 695,
    offerPrice: 695,
    rating: 4.2,
    reviewCount: 335,
    stock: 45,
    badge: "Value Pick",
    features: ["50dB ANC", "13.6mm Drivers", "360 Spatial Audio", "45ms Low Latency", "38hrs Playback"],
    specifications: { Brand: "realme", "Model Name": "Buds Wireless 5", Type: "Neckband", "Noise Cancellation": "50dB", Battery: "38hrs" },
  },

  /* ------------------------------ WEARABLES ------------------------------ */
  {
    id: "wea-001",
    name: "Apple Watch Ultra 3 GPS + Cellular 49mm Natural Titanium Case",
    slug: "apple-watch-ultra-3",
    description: "Apple Watch Ultra 3 with GPS + Cellular, 49mm titanium case, and premium design.",
    category: "Wearables",
    image: "https://m.media-amazon.com/images/I/81P33VrD8oL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81P33VrD8oL._SL1500_.jpg"],
    originalPrice: 89900,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.7,
    reviewCount: 475,
    stock: 6,
    badge: "Premium",
    features: ["GPS + Cellular", "49mm Titanium Case", "Premium Design", "Advanced Health Features", "Durable Build"],
    specifications: { Brand: "Apple", "Model Name": "Watch Ultra 3", Case: "49mm Titanium", GPS: "Yes", Cellular: "Yes" },
  },
  {
    id: "wea-002",
    name: "Fire-Boltt Clickk 54.1mm (2.12 inch) AMOLED Display, Front Camera, Nano SIM Slot",
    slug: "fire-boltt-clickk",
    description: "Fire-Boltt Clickk smartwatch with 2.12-inch AMOLED display, front camera, and Nano SIM slot.",
    category: "Wearables",
    image: "https://m.media-amazon.com/images/I/71IaFbvnsHL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71IaFbvnsHL._SL1500_.jpg"],
    originalPrice: 24999,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.3,
    reviewCount: 399,
    stock: 20,
    badge: "Hot Deal",
    features: ["AMOLED Display", "Front Camera", "Nano SIM Slot", "1000mAh Battery", "Smart Features"],
    specifications: { Brand: "Fire-Boltt", "Model Name": "Clickk", Display: "2.12 inch AMOLED", Battery: "1000mAh", "SIM Slot": "Nano SIM" },
  },
  {
    id: "wea-003",
    name: "Amazfit Cheetah Lightweight Running 44mm Smart Watch with Dual-Band GPS",
    slug: "amazfit-cheetah",
    description: "Amazfit Cheetah running smartwatch with dual-band GPS, route navigation, and offline maps.",
    category: "Wearables",
    image: "https://m.media-amazon.com/images/I/71SWMYfThnL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71SWMYfThnL._SL1500_.jpg"],
    originalPrice: 25999,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.5,
    reviewCount: 395,
    stock: 15,
    badge: "Best Seller",
    features: ["Dual-Band GPS", "Route Navigation", "Offline Maps", "Personalized Training Plans", "HR & SpO2"],
    specifications: { Brand: "Amazfit", "Model Name": "Cheetah", Display: "44mm", GPS: "Dual-Band", "Water Resistance": "5ATM" },
  },
  {
    id: "wea-004",
    name: "OnePlus Watch 2R with Wear OS 4 by Google, Snapdragon W5 Chipset",
    slug: "oneplus-watch-2r",
    description: "OnePlus Watch 2R with Wear OS 4, Snapdragon W5 chipset, and up to 100hrs battery life.",
    category: "Wearables",
    image: "https://m.media-amazon.com/images/I/71bfBylbT2L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71bfBylbT2L._SL1500_.jpg"],
    originalPrice: 19999,
    salePrice: 562,
    offerPrice: 562,
    rating: 4.5,
    reviewCount: 387,
    stock: 18,
    badge: "Best Seller",
    features: ["Wear OS 4", "Snapdragon W5 Chipset", "100hrs Battery Life", "1.43 AMOLED Display", "Dual Frequency GPS"],
    specifications: { Brand: "OnePlus", "Model Name": "Watch 2R", Display: "1.43 AMOLED", Battery: "100hrs", GPS: "Dual Frequency" },
  },
  {
    id: "wea-005",
    name: "Samsung Galaxy Watch Ultra Smartwatch - 2025 Version, 47mm, Titanium, LTE",
    slug: "samsung-galaxy-watch-ultra",
    description: "Samsung Galaxy Watch Ultra with titanium casing, AI-powered health monitoring, and LTE connectivity.",
    category: "Wearables",
    image: "https://m.media-amazon.com/images/I/81i1Vn-KQuL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81i1Vn-KQuL._SL1500_.jpg"],
    originalPrice: 69999,
    salePrice: 745,
    offerPrice: 745,
    rating: 4.7,
    reviewCount: 475,
    stock: 5,
    badge: "Premium",
    features: ["47mm Titanium", "LTE Connectivity", "AI-Powered Health Monitoring", "Durable Casing", "Quick Button"],
    specifications: { Brand: "Samsung", "Model Name": "Galaxy Watch Ultra", Case: "47mm Titanium", LTE: "Yes", Health: "AI-Powered" },
  },
  {
    id: "wea-006",
    name: "AGEasy Protec Fall Detection Smartwatch for Seniors with 4G LTE Calling, SOS Button",
    slug: "ageasy-protec-smartwatch",
    description: "AGEasy Protec smartwatch for seniors with fall detection, 4G LTE calling, and SOS button.",
    category: "Wearables",
    image: "https://m.media-amazon.com/images/I/61pFk3yU4BL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61pFk3yU4BL._SL1500_.jpg"],
    originalPrice: 24999,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.4,
    reviewCount: 405,
    stock: 20,
    badge: "Best Seller",
    features: ["Fall Detection", "4G LTE Calling", "SOS Button", "1.28 AMOLED Display", "Pill Reminder"],
    specifications: { Brand: "AGEasy", "Model Name": "Protec", Display: "1.28 AMOLED", LTE: "4G", "Water Resistance": "IP68" },
  },

  /* ----------------------------- APPLIANCES ----------------------------- */
  {
    id: "app-001",
    name: "LG 1.5 Ton 5 Star DUAL Inverter Split AC (Copper, AI Convertible 6-in-1 Cooling)",
    slug: "lg-1-5-ton-5-star-ac",
    description: "LG 1.5 Ton 5 Star DUAL Inverter Split AC with copper, AI Convertible 6-in-1 cooling, and HD filter.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/815QEibJCwL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/815QEibJCwL._SL1500_.jpg"],
    originalPrice: 47999,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.5,
    reviewCount: 455,
    stock: 10,
    badge: "Best Seller",
    features: ["1.5 Ton", "5 Star Rating", "DUAL Inverter", "AI Convertible 6-in-1 Cooling", "HD Filter"],
    specifications: { Brand: "LG", "Model Name": "TS-Q19YNZE", Tonnage: "1.5 Ton", "Star Rating": "5 Star", Type: "Split AC", "Energy Efficiency": "Yes" },
  },
  {
    id: "app-002",
    name: "Samsung 10.5 kg, 5 star, Semi-Automatic Top Load Washing Machine",
    slug: "samsung-10-5kg-washing-machine",
    description: "Samsung 10.5 kg semi-automatic top load washing machine with 5 star rating and air turbo drying.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/71Jzk3voA5L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71Jzk3voA5L._SL1500_.jpg"],
    originalPrice: 20499,
    salePrice: 421,
    offerPrice: 421,
    rating: 4.3,
    reviewCount: 399,
    stock: 15,
    badge: "Hot Deal",
    features: ["10.5 kg Capacity", "5 Star Rating", "Semi-Automatic", "Top Load", "Air Turbo Drying"],
    specifications: { Brand: "Samsung", "Model Name": "WT10C4260GG/TL", Capacity: "10.5 kg", Type: "Semi-Automatic Top Load", "Star Rating": "5 Star" },
  },
  {
    id: "app-003",
    name: "Samsung 653 L, 3 Star, Frost Free, Double Door, Convertible 5-in-1 Digital Inverter Refrigerator",
    slug: "samsung-653l-refrigerator",
    description: "Samsung 653L side-by-side refrigerator with convertible 5-in-1 digital inverter and AI-enabled smart features.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/61kqXpSm6eL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61kqXpSm6eL._SL1500_.jpg"],
    originalPrice: 113000,
    salePrice: 526,
    offerPrice: 526,
    rating: 4.6,
    reviewCount: 485,
    stock: 4,
    badge: "Premium",
    features: ["653L Capacity", "Convertible 5-in-1", "Digital Inverter", "AI Enabled", "Smart Refrigerator"],
    specifications: { Brand: "Samsung", "Model Name": "RS76CG8003S9HL", Capacity: "653L", Type: "Side-by-Side", "Star Rating": "3 Star", "Frost Free": "Yes" },
  },
  {
    id: "app-004",
    name: "Samsung 385 L, 2 Star, Convertible 5-in-1 Digital Inverter, Double Door Refrigerator",
    slug: "samsung-385l-refrigerator",
    description: "Samsung 385L double door refrigerator with convertible 5-in-1 digital inverter and display.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/71TjGLTupQL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71TjGLTupQL._SL1500_.jpg"],
    originalPrice: 43999,
    salePrice: 635,
    offerPrice: 635,
    rating: 4.4,
    reviewCount: 465,
    stock: 8,
    badge: "Best Seller",
    features: ["385L Capacity", "Convertible 5-in-1", "Digital Inverter", "Display", "Frost Free"],
    specifications: { Brand: "Samsung", "Model Name": "RT42C5532S9/HL", Capacity: "385L", Type: "Double Door", "Star Rating": "2 Star" },
  },
  {
    id: "app-005",
    name: "Samsung 8 kg, 5 star, Eco Bubble Technology, AI Control, Wi-Fi, Fully-Automatic Front Load",
    slug: "samsung-8kg-front-load-washing-machine",
    description: "Samsung 8kg front-load washing machine with Eco Bubble Technology, AI Control, and Wi-Fi.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/71YN8gtRCXL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71YN8gtRCXL._SL1500_.jpg"],
    originalPrice: 55990,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.5,
    reviewCount: 417,
    stock: 10,
    badge: "Best Seller",
    features: ["8 kg Capacity", "5 Star Rating", "Eco Bubble Technology", "AI Control", "Wi-Fi Enabled"],
    specifications: { Brand: "Samsung", "Model Name": "WW80T504DAX1TL", Capacity: "8 kg", Type: "Fully-Automatic Front Load", "Star Rating": "5 Star" },
  },
  {
    id: "app-006",
    name: "Samsung 1.5 Ton 5 Star (5-in-1 Convertible Cooling, 2025 Model) Inverter Split AC",
    slug: "samsung-1-5-ton-5-star-ac",
    description: "Samsung 1.5 Ton 5 Star inverter split AC with 5-in-1 convertible cooling and stabilizer free operation.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/51Ng7N+PcBL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51Ng7N+PcBL._SL1500_.jpg"],
    originalPrice: 72990,
    salePrice: 526,
    offerPrice: 526,
    rating: 4.4,
    reviewCount: 427,
    stock: 8,
    badge: "Hot Deal",
    features: ["1.5 Ton", "5 Star Rating", "5-in-1 Convertible Cooling", "Stabilizer Free", "Inverter Split AC"],
    specifications: { Brand: "Samsung", "Model Name": "AR18CYNZABE", Tonnage: "1.5 Ton", "Star Rating": "5 Star", Type: "Split AC" },
  },
  {
    id: "app-007",
    name: "Blue Star 1.5 Ton 5 Star Smart Wi-Fi Inverter Split AC (Copper, Convertible 5 in 1 Cooling)",
    slug: "blue-star-1-5-ton-ac",
    description: "Blue Star 1.5 Ton 5 Star smart Wi-Fi inverter split AC with convertible 5 in 1 cooling.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/51q4Camw0uL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51q4Camw0uL._SL1500_.jpg"],
    originalPrice: 75000,
    salePrice: 652,
    offerPrice: 652,
    rating: 4.3,
    reviewCount: 432,
    stock: 6,
    badge: "Best Seller",
    features: ["1.5 Ton", "5 Star Rating", "Smart Wi-Fi", "Inverter", "Convertible 5 in 1 Cooling"],
    specifications: { Brand: "Blue Star", "Model Name": "IC518YNURS", Tonnage: "1.5 Ton", "Star Rating": "5 Star", Type: "Split AC", "Smart Features": "Wi-Fi" },
  },
  {
    id: "app-008",
    name: "Godrej 472 L 2 Star With AI Tech, 1+2 Years Additional Warranty, 6-In-1 Convertible Freezer",
    slug: "godrej-472l-refrigerator",
    description: "Godrej 472L double door refrigerator with AI tech, 6-in-1 convertible freezer, and additional warranty.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/61v22CjWv6L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61v22CjWv6L._SL1500_.jpg"],
    originalPrice: 75000,
    salePrice: 521,
    offerPrice: 521,
    rating: 4.3,
    reviewCount: 465,
    stock: 5,
    badge: "Best Seller",
    features: ["472L Capacity", "AI Tech", "6-in-1 Convertible Freezer", "Additional Warranty", "Frost Free"],
    specifications: { Brand: "Godrej", "Model Name": "RF EON 474B RCI CH GD", Capacity: "472L", Type: "Double Door", "Star Rating": "2 Star" },
  },
  {
    id: "app-009",
    name: "AGARO Regency Air Fryer For Home, 12L, Family Rotisserie Oven, 1800W",
    slug: "agaro-regency-air-fryer",
    description: "AGARO Regency 12L air fryer with rotisserie oven, 1800W, and 9 preset menus.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/71kXAZ5OprL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71kXAZ5OprL._SL1500_.jpg"],
    originalPrice: 59900,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.4,
    reviewCount: 419,
    stock: 12,
    badge: "Hot Deal",
    features: ["12L Capacity", "Family Rotisserie Oven", "1800W", "9 Preset Menu", "Air Fryer Toaster Oven"],
    specifications: { Brand: "AGARO", "Model Name": "Regency", Capacity: "12L", Power: "1800W", Type: "Air Fryer" },
  },
  {
    id: "app-010",
    name: "atomberg Renesa 400mm Pedestal Fan for Home | Silent BLDC Stand Fan",
    slug: "atomberg-renesa-fan",
    description: "atomberg Renesa 400mm pedestal fan with silent BLDC motor, LED display, and remote control.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/710CFw58+gL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/710CFw58+gL._SL1500_.jpg"],
    originalPrice: 6999,
    salePrice: 632,
    offerPrice: 632,
    rating: 4.2,
    reviewCount: 395,
    stock: 25,
    badge: "Value Pick",
    features: ["400mm", "BLDC Motor", "Silent Operation", "LED Display", "Remote Control"],
    specifications: { Brand: "atomberg", "Model Name": "Renesa", Size: "400mm", Type: "Pedestal Fan", Motor: "BLDC" },
  },

  /* ----------------------------- HOME & KITCHEN ----------------------------- */
  {
    id: "hom-001",
    name: "Aquaguard Ritz Pro RO+UV+Copper | Stainless Steel Tank | 2 year filter life",
    slug: "aquaguard-ritz-pro",
    description: "Aquaguard Ritz Pro water purifier with RO+UV+Copper, stainless steel tank, and 2 year filter life.",
    category: "Home & Kitchen",
    image: "https://m.media-amazon.com/images/I/51lMbq8TQgL._SL1100_.jpg",
    images: ["https://m.media-amazon.com/images/I/51lMbq8TQgL._SL1100_.jpg"],
    originalPrice: 32999,
    salePrice: 562,
    offerPrice: 562,
    rating: 4.4,
    reviewCount: 415,
    stock: 10,
    badge: "Best Seller",
    features: ["RO+UV+Copper", "Stainless Steel Tank", "2 Year Filter Life", "SMART Purifier", "9 Stage Purification"],
    specifications: { Brand: "Aquaguard", "Model Name": "Ritz Pro", Purification: "RO+UV+Copper", Tank: "Stainless Steel", "Filter Life": "2 Years" },
  },
  {
    id: "hom-002",
    name: "Philips India's No.1 Men's Trimmer | Patented Twin Trim Blades | Precision Trimming",
    slug: "philips-mens-trimmer",
    description: "Philips men's trimmer with patented twin trim blades, 13-in-1 kit, and 120 min runtime.",
    category: "Home & Kitchen",
    image: "https://m.media-amazon.com/images/I/61Bd7dkoi2L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61Bd7dkoi2L._SL1500_.jpg"],
    originalPrice: 7999,
    salePrice: 563,
    offerPrice: 563,
    rating: 4.3,
    reviewCount: 339,
    stock: 30,
    badge: "Best Seller",
    features: ["Patented Twin Trim Blades", "13-in-1 Kit", "120 Min Runtime", "5 Min Quick Charge", "2 Year Warranty"],
    specifications: { Brand: "Philips", "Model Name": "MG7920/65", Type: "Men's Trimmer", Runtime: "120 min", "Warranty": "2 Years" },
  },
  {
    id: "hom-003",
    name: "Bajaj 500 Watt GX-1 Mixer Grinder with 3 Jars",
    slug: "bajaj-mixer-grinder",
    description: "Bajaj GX-1 mixer grinder with 500W motor and 3 jars for versatile grinding.",
    category: "Home & Kitchen",
    image: "https://m.media-amazon.com/images/I/51RDpv5updL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51RDpv5updL._SL1500_.jpg"],
    originalPrice: 4999,
    salePrice: 561,
    offerPrice: 561,
    rating: 4.1,
    reviewCount: 390,
    stock: 35,
    badge: "Value Pick",
    features: ["500W Motor", "3 Jars", "Mixer Grinder", "Compact Design", "Easy to Clean"],
    specifications: { Brand: "Bajaj", "Model Name": "GX-1", Power: "500W", Jars: "3", Type: "Mixer Grinder" },
  },
  {
    id: "hom-004",
    name: "Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jar + 1 Juicer Jar",
    slug: "prestige-iris-mixer-grinder",
    description: "Prestige Iris mixer grinder with 750W motor, 3 stainless steel jars, and 1 juicer jar.",
    category: "Home & Kitchen",
    image: "https://m.media-amazon.com/images/I/71qiTDQrBQL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71qiTDQrBQL._SL1500_.jpg"],
    originalPrice: 5295,
    salePrice: 456,
    offerPrice: 456,
    rating: 4.2,
    reviewCount: 395,
    stock: 28,
    badge: "Best Seller",
    features: ["750W Motor", "3 Stainless Steel Jars", "1 Juicer Jar", "Premium Design", "Powerful Grinding"],
    specifications: { Brand: "Prestige", "Model Name": "Iris", Power: "750W", Jars: "3+1", Type: "Mixer Grinder" },
  },

  /* ----------------------------- ACCESSORIES & OTHER ----------------------------- */
  {
    id: "acc-001",
    name: "Xiaomi Power Bank 4i 20000mAh 33W Super Fast Charging PD | Power Delivery | QC 3.0",
    slug: "xiaomi-power-bank-4i",
    description: "Xiaomi Power Bank 4i with 20000mAh capacity, 33W super fast charging, and triple output ports.",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/51c5j0aJtYL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51c5j0aJtYL._SL1500_.jpg"],
    originalPrice: 2599,
    salePrice: 452,
    offerPrice: 452,
    rating: 4.3,
    reviewCount: 319,
    stock: 50,
    badge: "Best Seller",
    features: ["20000mAh Capacity", "33W Super Fast Charging", "PD & QC 3.0", "Triple Output Ports", "Type C Input"],
    specifications: { Brand: "Xiaomi", "Model Name": "Power Bank 4i", Capacity: "20000mAh", Charging: "33W", Ports: "Triple Output" },
  },
  {
    id: "acc-002",
    name: "WZATCO Yuva Ultra, Ultra Bright 770 ANSI, 590 ISO Lumens, Native 1080P Projector",
    slug: "wzatco-yuva-ultra-projector",
    description: "WZATCO Yuva Ultra projector with 770 ANSI lumens, native 1080P, and Android TV.",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/611qZLjar1L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/611qZLjar1L._SL1500_.jpg"],
    originalPrice: 29990,
    salePrice: 412,
    offerPrice: 412,
    rating: 4.3,
    reviewCount: 339,
    stock: 8,
    badge: "Hot Deal",
    features: ["770 ANSI Lumens", "590 ISO Lumens", "Native 1080P", "Android TV", "Fully Automatic"],
    specifications: { Brand: "WZATCO", "Model Name": "Yuva Ultra", Brightness: "770 ANSI", Resolution: "1080P", Smart: "Android TV" },
  },
  {
    id: "acc-003",
    name: "IZI Spectra Drone with Camera 4K HDR Cinematic, 1 CMOS sensor, 102 Min Flight",
    slug: "izi-spectra-drone",
    description: "IZI Spectra drone with 4K HDR camera, 102 min flight time, and 3-axis gimbal.",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/71wXJYrZooL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71wXJYrZooL._SL1500_.jpg"],
    originalPrice: 699990,
    salePrice: 436,
    offerPrice: 436,
    rating: 4.7,
    reviewCount: 999,
    stock: 3,
    badge: "Flagship",
    features: ["4K HDR Cinematic", "102 Min Flight", "3-Axis Gimbal", "GPS Drone", "Omni Obstacle Sensor"],
    specifications: { Brand: "IZI", "Model Name": "Spectra", Camera: "4K HDR", Flight: "102 Min", Gimbal: "3-Axis", GPS: "Yes" },
  },
  {
    id: "acc-004",
    name: "American Tourister Ivy Nxt 3PCSET 4 Spinner Wheels Hard Luggage Polycarbonate",
    slug: "american-tourister-ivy-nxt",
    description: "American Tourister Ivy Nxt 3-piece hard luggage set with 4 spinner wheels and TSA lock.",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/51FW5M0mpnL._SL1080_.jpg",
    images: ["https://m.media-amazon.com/images/I/51FW5M0mpnL._SL1080_.jpg"],
    originalPrice: 25700,
    salePrice: 352,
    offerPrice: 352,
    rating: 4.3,
    reviewCount: 399,
    stock: 12,
    badge: "Best Seller",
    features: ["3-Piece Set", "4 Spinner Wheels", "Hard Case", "Polycarbonate", "TSA Lock"],
    specifications: { Brand: "American Tourister", "Model Name": "Ivy Nxt", Set: "3-Piece", Wheels: "4 Spinner", Material: "Polycarbonate" },
  },
  {
    id: "acc-005",
    name: "Safari Pentagon Pro 8 Wheels Set of 3 (Cabin + Medium + Large) Trolley Bags",
    slug: "safari-pentagon-pro",
    description: "Safari Pentagon Pro 3-piece luggage set with 8 wheels, hard case polypropylene, and 360 wheeling.",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/61wU7VJsTbL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61wU7VJsTbL._SL1500_.jpg"],
    originalPrice: 33999,
    salePrice: 362,
    offerPrice: 362,
    rating: 4.4,
    reviewCount: 395,
    stock: 10,
    badge: "Hot Deal",
    features: ["8 Wheels", "3-Piece Set", "Hard Case", "Polypropylene", "360 Wheeling"],
    specifications: { Brand: "Safari", "Model Name": "Pentagon Pro", Set: "3-Piece", Wheels: "8", Material: "Polypropylene" },
  },
  {
    id: "acc-006",
    name: "Skybags Large Trooper Check-in Size Hard Luggage with 4 Spinner Wheels",
    slug: "skybags-trooper-luggage",
    description: "Skybags Trooper hard luggage with 4 spinner wheels and resettable combination lock.",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/71ZgVRNR3qL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71ZgVRNR3qL._SL1500_.jpg"],
    originalPrice: 10920,
    salePrice: 412,
    offerPrice: 412,
    rating: 4.2,
    reviewCount: 375,
    stock: 15,
    badge: "Value Pick",
    features: ["Large Check-in Size", "4 Spinner Wheels", "Resettable Combination Lock", "Hard Case", "Durable Build"],
    specifications: { Brand: "Skybags", "Model Name": "Trooper", Type: "Check-in Luggage", Wheels: "4 Spinner", Lock: "Combination" },
  },
  {
    id: "acc-007",
    name: "Arctic Hunter Backpack for Men Women 30L Office Casual 15.6-inch Laptop Bag",
    slug: "arctic-hunter-backpack",
    description: "Arctic Hunter backpack with 30L capacity, 15.6-inch laptop compartment, and USB port.",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/71kVQOhWKKL._SX679_.jpg",
    images: ["https://m.media-amazon.com/images/I/71kVQOhWKKL._SX679_.jpg"],
    originalPrice: 5999,
    salePrice: 421,
    offerPrice: 421,
    rating: 4.2,
    reviewCount: 417,
    stock: 25,
    badge: "Best Seller",
    features: ["30L Capacity", "15.6-inch Laptop Compartment", "USB Port", "Water-resistant", "Multi-pockets"],
    specifications: { Brand: "Arctic Hunter", Type: "Backpack", Capacity: "30L", Laptop: "15.6-inch", USB: "Yes" },
  },
  {
    id: "acc-008",
    name: "Philips Viva Collection HD4928/01 2100-Watt Induction Cooktop",
    slug: "philips-induction-cooktop",
    description: "Philips Viva Collection induction cooktop with 2100W power and crystal glass design.",
    category: "Home & Kitchen",
    image: "https://m.media-amazon.com/images/I/715L3WOq4JL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/715L3WOq4JL._SL1500_.jpg"],
    originalPrice: 5999,
    salePrice: 632,
    offerPrice: 632,
    rating: 4.2,
    reviewCount: 376,
    stock: 20,
    badge: "Best Seller",
    features: ["2100W", "Crystal Glass", "Soft Touch Button", "Induction Cooktop", "Viva Collection"],
    specifications: { Brand: "Philips", "Model Name": "HD4928/01", Power: "2100W", Type: "Induction Cooktop" },
  },

  /* ----------------------------- HOME & FURNITURE ----------------------------- */
  {
    id: "fur-001",
    name: "Crompton Marvel Neo Inverter Compatible Portable Personal Air Cooler (40L, White)",
    slug: "crompton-marvel-neo-cooler",
    description: "Crompton Marvel Neo portable air cooler with 40L capacity and inverter compatibility.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/41V0bcp5nsL._SL1000_.jpg",
    images: ["https://m.media-amazon.com/images/I/41V0bcp5nsL._SL1000_.jpg"],
    originalPrice: 10900,
    salePrice: 512,
    offerPrice: 512,
    rating: 4.1,
    reviewCount: 397,
    stock: 18,
    badge: "Value Pick",
    features: ["40L Capacity", "Inverter Compatible", "Portable", "Personal Cooler", "Energy Efficient"],
    specifications: { Brand: "Crompton", "Model Name": "Marvel Neo", Capacity: "40L", Type: "Air Cooler" },
  },
  {
    id: "fur-002",
    name: "Symphony Diet 3D 30i Personal Tower Air Cooler for Home with Honeycomb Pad",
    slug: "symphony-diet-3d-cooler",
    description: "Symphony Diet 3D 30i tower air cooler with honeycomb pad and i-Pure technology.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/61tLj6CIW-L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61tLj6CIW-L._SL1500_.jpg"],
    originalPrice: 9999,
    salePrice: 361,
    offerPrice: 361,
    rating: 4.2,
    reviewCount: 325,
    stock: 20,
    badge: "Best Seller",
    features: ["Personal Tower", "Honeycomb Pad", "i-Pure Technology", "Low Power Consumption", "12L Capacity"],
    specifications: { Brand: "Symphony", "Model Name": "Diet 3D 30i", Capacity: "12L", Type: "Tower Air Cooler" },
  },
  {
    id: "fur-003",
    name: "Crompton Ozone Desert Air Cooler- 55L; with Everlast Pump, Auto Fill",
    slug: "crompton-ozone-cooler",
    description: "Crompton Ozone desert air cooler with 55L capacity, Everlast pump, and auto fill.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/51aDYb93xaL._SX679_.jpg",
    images: ["https://m.media-amazon.com/images/I/51aDYb93xaL._SX679_.jpg"],
    originalPrice: 2499,
    salePrice: 412,
    offerPrice: 412,
    rating: 4.0,
    reviewCount: 233,
    stock: 30,
    badge: "Value Pick",
    features: ["55L Capacity", "Everlast Pump", "Auto Fill", "4-Way Air Deflection", "High Density Honeycomb"],
    specifications: { Brand: "Crompton", "Model Name": "Ozone", Capacity: "55L", Type: "Desert Air Cooler" },
  },
  {
    id: "fur-004",
    name: "ACTIVA Gracia 1200 MM (28 Watts) BLDC Motor Fan With LED Light | Remote",
    slug: "activa-gracia-fan",
    description: "ACTIVA Gracia ceiling fan with 1200mm sweep, BLDC motor, and LED light.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/51CbiNYdkbL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/51CbiNYdkbL._SL1500_.jpg"],
    originalPrice: 2999,
    salePrice: 231,
    offerPrice: 231,
    rating: 4.0,
    reviewCount: 315,
    stock: 25,
    badge: "Value Pick",
    features: ["1200mm Sweep", "BLDC Motor", "LED Light", "Remote Control", "Energy Saving"],
    specifications: { Brand: "ACTIVA", "Model Name": "Gracia", Sweep: "1200mm", Motor: "BLDC", Type: "Ceiling Fan" },
  },
  {
    id: "fur-005",
    name: "ACTIVA Lotus 5 Star 1200 mm BLDC Motor with Remote 4 Blade Ceiling Fan",
    slug: "activa-lotus-fan",
    description: "ACTIVA Lotus ceiling fan with 5 star rating, BLDC motor, and remote control.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/61jFJYw6qyL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61jFJYw6qyL._SL1500_.jpg"],
    originalPrice: 3699,
    salePrice: 231,
    offerPrice: 231,
    rating: 4.1,
    reviewCount: 310,
    stock: 20,
    badge: "Best Seller",
    features: ["5 Star Rating", "BLDC Motor", "Remote Control", "4 Blade", "Premium Design"],
    specifications: { Brand: "ACTIVA", "Model Name": "Lotus", Sweep: "1200mm", Motor: "BLDC", Rating: "5 Star" },
  },
  {
    id: "fur-006",
    name: "V-Guard Esfera 3 Blade Pedestal Fan With Remote Control | Adjustable Height",
    slug: "v-guard-esfera-fan",
    description: "V-Guard Esfera pedestal fan with remote control, adjustable height, and 100% copper motor.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/81k5hi1+WjL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81k5hi1+WjL._SL1500_.jpg"],
    originalPrice: 3339,
    salePrice: 236,
    offerPrice: 236,
    rating: 4.2,
    reviewCount: 369,
    stock: 22,
    badge: "Best Seller",
    features: ["Remote Control", "Adjustable Height", "100% Copper Motor", "3 Blade", "High Speed"],
    specifications: { Brand: "V-Guard", "Model Name": "Esfera", Type: "Pedestal Fan", Motor: "Copper" },
  },

  /* ----------------------------- GAMING & MORE ----------------------------- */
  {
    id: "gam-001",
    name: "Sony PlayStation5 Gaming Console (Slim)",
    slug: "sony-playstation-5-slim",
    description: "Sony PlayStation5 Slim gaming console with advanced gaming features.",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/51ljnEaW0pL._SL1000_.jpg",
    images: ["https://m.media-amazon.com/images/I/51ljnEaW0pL._SL1000_.jpg"],
    originalPrice: 54990,
    salePrice: 241,
    offerPrice: 241,
    rating: 4.7,
    reviewCount: 466,
    stock: 8,
    badge: "Best Seller",
    features: ["PS5 Slim", "Gaming Console", "High Performance", "4K Gaming", "Advanced Graphics"],
    specifications: { Brand: "Sony", "Model Name": "PlayStation5", Type: "Gaming Console", Version: "Slim" },
  },
  {
    id: "gam-002",
    name: "ZEBRONICS Bluetooth 4.1 Speaker with FM, USB, SD Card Slot and Remote Indie (105W)",
    slug: "zebronics-indie-speaker",
    description: "ZEBRONICS Indie speaker with 105W power, Bluetooth 4.1, FM, USB, and SD card slot.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/81v7Q8REdLL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81v7Q8REdLL._SL1500_.jpg"],
    originalPrice: 8499,
    salePrice: 236,
    offerPrice: 236,
    rating: 4.1,
    reviewCount: 393,
    stock: 15,
    badge: "Value Pick",
    features: ["105W Power", "Bluetooth 4.1", "FM, USB, SD Card", "Remote Control", "Indie Design"],
    specifications: { Brand: "ZEBRONICS", "Model Name": "Indie", Power: "105W", Connectivity: "Bluetooth 4.1" },
  },
  {
    id: "gam-003",
    name: "boAt Partypal 390 Speaker with 160 W Signature Sound, Up to 6 hrs Playtime",
    slug: "boat-partypal-390",
    description: "boAt Partypal 390 speaker with 160W signature sound and karaoke mic.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/81piwlskHKL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81piwlskHKL._SL1500_.jpg"],
    originalPrice: 34990,
    salePrice: 289,
    offerPrice: 289,
    rating: 4.5,
    reviewCount: 473,
    stock: 10,
    badge: "Hot Deal",
    features: ["160W Sound", "Karaoke Mic", "EQ Modes", "TWS Mode", "Bluetooth v5.3"],
    specifications: { Brand: "boAt", "Model Name": "Partypal 390", Power: "160W", Playtime: "6hrs", Bluetooth: "v5.3" },
  },
  {
    id: "gam-004",
    name: "HP Laserjet Pro M126nw Multi-Function Monochrome Laser Printer",
    slug: "hp-laserjet-pro-m126nw",
    description: "HP Laserjet Pro M126nw multi-function monochrome laser printer for home and office.",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/61D4JNRme0L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61D4JNRme0L._SL1500_.jpg"],
    originalPrice: 24999,
    salePrice: 246,
    offerPrice: 246,
    rating: 4.3,
    reviewCount: 437,
    stock: 12,
    badge: "Best Seller",
    features: ["Multi-Function", "Monochrome Laser", "Print, Scan, Copy", "Wi-Fi", "Fast Printing"],
    specifications: { Brand: "HP", "Model Name": "Laserjet Pro M126nw", Type: "Laser Printer", Function: "Multi-Function" },
  },
  {
    id: "gam-005",
    name: "NINETY ONE Limited Edition Manchester 27.5T 21 Speed Shimano ACERA Gears Alloy Bike",
    slug: "ninety-one-manchester-bike",
    description: "NINETY ONE Manchester hybrid bike with 21-speed Shimano ACERA gears and dual disc brakes.",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/71IPSR-ZQSL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71IPSR-ZQSL._SL1500_.jpg"],
    originalPrice: 30999,
    salePrice: 274,
    offerPrice: 274,
    rating: 4.4,
    reviewCount: 435,
    stock: 6,
    badge: "Hot Deal",
    features: ["27.5T", "21 Speed", "Shimano ACERA Gears", "Dual Disc Brake", "Alloy Bike"],
    specifications: { Brand: "NINETY ONE", "Model Name": "Manchester", Type: "Hybrid Bike", Gears: "21 Speed", Brake: "Dual Disc" },
  },
  {
    id: "gam-006",
    name: "Cultsport Davie 7HP Peak, Max Weight: 150 Kg, Auto Incline with Massager Treadmill",
    slug: "cultsport-davie-treadmill",
    description: "Cultsport Davie treadmill with 7HP peak motor, auto incline, and massager function.",
    category: "Appliances",
    image: "https://m.media-amazon.com/images/I/51D84IjJ6QL._SL1100_.jpg",
    images: ["https://m.media-amazon.com/images/I/51D84IjJ6QL._SL1100_.jpg"],
    originalPrice: 100999,
    salePrice: 356,
    offerPrice: 356,
    rating: 4.4,
    reviewCount: 467,
    stock: 4,
    badge: "Premium",
    features: ["7HP Peak", "Max Weight 150 Kg", "Auto Incline", "Massager", "Motorized Treadmill"],
    specifications: { Brand: "Cultsport", "Model Name": "Davie", Motor: "7HP", maxSize: "150 Kg", Type: "Treadmill" },
  },
  {
    id: "gam-007",
    name: "Kuvings B1700 Dark Red Professional Cold Press Whole Slow Juicer",
    slug: "kuvings-b1700-juicer",
    description: "Kuvings B1700 professional cold press juicer with 240W motor and Patented JMCS Technology.",
    category: "Home & Kitchen",
    image: "https://m.media-amazon.com/images/I/71IZLQ11KcL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71IZLQ11KcL._SL1500_.jpg"],
    originalPrice: 35900,
    salePrice: 345,
    offerPrice: 345,
    rating: 4.5,
    reviewCount: 393,
    stock: 6,
    badge: "Best Seller",
    features: ["Cold Press", "240W Motor", "Patented JMCS Technology", "10% More Juice", "Professional Juicer"],
    specifications: { Brand: "Kuvings", "Model Name": "B1700", Power: "240W", Type: "Cold Press Juicer" },
  },
  {
    id: "gam-008",
    name: "OBAGE Newly Launched Ultra-10 250W 2.1 Home Theatre System with 10 Woofer",
    slug: "obage-ultra-10-speakers",
    description: "OBAGE Ultra-10 2.1 home theatre system with 250W power and 10-inch woofer.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/81C3MZnWZDL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81C3MZnWZDL._SL1500_.jpg"],
    originalPrice: 19999,
    salePrice: 365,
    offerPrice: 365,
    rating: 4.3,
    reviewCount: 418,
    stock: 10,
    badge: "Hot Deal",
    features: ["250W Power", "2.1 Home Theatre", "10-inch Woofer", "HDMI ARC", "Bluetooth V5.3"],
    specifications: { Brand: "OBAGE", "Model Name": "Ultra-10", Power: "250W", Type: "Home Theatre", Woofer: "10-inch" },
  },
  {
    id: "gam-009",
    name: "SONY SRS-XP700 with IPX4 Splashproof Protection, 25hrs Battery Portable Wireless Party Speaker",
    slug: "sony-srs-xp700",
    description: "Sony SRS-XP700 portable wireless party speaker with IPX4 splashproof and 25hrs battery.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/81CChBWuhRS._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/81CChBWuhRS._SL1500_.jpg"],
    originalPrice: 37999,
    salePrice: 426,
    offerPrice: 426,
    rating: 4.5,
    reviewCount: 463,
    stock: 8,
    badge: "Best Seller",
    features: ["IPX4 Splashproof", "25hrs Battery", "Portable", "Party Speaker", "Wireless"],
    specifications: { Brand: "SONY", "Model Name": "SRS-XP700", Battery: "25hrs", Waterproof: "IPX4", Type: "Party Speaker" },
  },
  {
    id: "gam-010",
    name: "Zeb-Juke Bar 9500WS Pro Dolby 5.1",
    slug: "zeb-juke-bar-9500ws",
    description: "Zeb-Juke Bar 9500WS Pro Dolby 5.1 soundbar with immersive audio experience.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/71eRAMvY25L._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/71eRAMvY25L._SL1500_.jpg"],
    originalPrice: 48990,
    salePrice: 346,
    offerPrice: 346,
    rating: 4.5,
    reviewCount: 477,
    stock: 7,
    badge: "Best Seller",
    features: ["Dolby 5.1", "Soundbar", "Immersive Audio", "Premium Design", "Home Theater"],
    specifications: { Brand: "Zeb-Juke", "Model Name": "Bar 9500WS Pro", Audio: "Dolby 5.1", Type: "Soundbar" },
  },
  {
    id: "gam-011",
    name: "Aavante Bar 3200D",
    slug: "aavante-bar-3200d",
    description: "Aavante Bar 3200D soundbar with powerful audio performance.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/61S2NC2VLEL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61S2NC2VLEL._SL1500_.jpg"],
    originalPrice: 39999,
    salePrice: 456,
    offerPrice: 456,
    rating: 4.4,
    reviewCount: 437,
    stock: 10,
    badge: "Best Seller",
    features: ["Soundbar", "Powerful Audio", "Home Theater", "Premium Build", "Immersive Sound"],
    specifications: { Brand: "Aavante", "Model Name": "Bar 3200D", Type: "Soundbar" },
  },
  {
    id: "gam-012",
    name: "Aavante Bar 3100D",
    slug: "aavante-bar-3100d",
    description: "Aavante Bar 3100D soundbar with immersive audio experience.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/61lC-uC+MSL._SL1500_.jpg",
    images: ["https://m.media-amazon.com/images/I/61lC-uC+MSL._SL1500_.jpg"],
    originalPrice: 14999,
    salePrice: 526,
    offerPrice: 526,
    rating: 4.3,
    reviewCount: 415,
    stock: 12,
    badge: "Value Pick",
    features: ["Soundbar", "Immersive Audio", "Home Theater", "Affordable", "Premium Sound"],
    specifications: { Brand: "Aavante", "Model Name": "Bar 3100D", Type: "Soundbar" },
  },
  {
    id: "gam-013",
    name: "Sony HT-S40R Real 5.1ch Dolby Audio Soundbar",
    slug: "sony-ht-s40r-soundbar",
    description: "Sony HT-S40R 5.1ch Dolby Audio soundbar with real surround sound experience.",
    category: "Audio",
    image: "https://m.media-amazon.com/images/I/51m4NsZau4L._SL1212_.jpg",
    images: ["https://m.media-amazon.com/images/I/51m4NsZau4L._SL1212_.jpg"],
    originalPrice: 47999,
    salePrice: 451,
    offerPrice: 451,
    rating: 4.6,
    reviewCount: 483,
    stock: 5,
    badge: "Best Seller",
    features: ["Real 5.1ch", "Dolby Audio", "Soundbar", "Surround Sound", "Home Theater"],
    specifications: { Brand: "Sony", "Model Name": "HT-S40R", Audio: "5.1ch Dolby", Type: "Soundbar" },
  },
]);

/* ------------------------------ Helpers ------------------------------ */

export function getAllProducts(): Product[] {
  return products;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase()
  );
}

export function getCategories(): string[] {
  return [...CATEGORIES];
}

export function getDealsOfTheDay(limit = 8): Product[] {
  return [...products]
    .sort((a, b) => b.discountPercentage - a.discountPercentage)
    .slice(0, limit);
}

export function getBestSelling(limit = 8): Product[] {
  return [...products]
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .slice(0, limit);
}

export function getMegaDeals(limit = 4): Product[] {
  const flagged = products.filter((p) => p.badge === "Mega Deal");
  const rest = products.filter((p) => p.badge !== "Mega Deal");
  return [...flagged, ...rest].slice(0, limit);
}

export function getProductsByIds(ids: string[]): Product[] {
  return products.filter((p) => ids.includes(p.id));
}